In [1]:
#-- Panda series. --#
#-- Import Pandas Library. --#
import pandas as pd
#-- Create Series. --#
temperatures = pd.Series([32, 35, 33, 34], index=["Mon", "Tues", "Wed", "Thurs"])
#-- Print the Series (Work like key-value in dictionary). --# 
print(temperatures)

Mon      32
Tues     35
Wed      33
Thurs    34
dtype: int64

In [2]:
#-- Pandas Dataframe. --#
data = {
    "Name": ["Alice", "Bob", "Charlie", "Diana"],
    "Age": [25, 30, 22, 28],
    "City": ["New York", "London", "Paris", "London"],
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris
3    Diana   28    London

In [6]:
#-- Read file. --#
student_grade_data = pd.read_csv('student_grade.csv')
#-- Print all file. --#
student_grade_data

,student_id,first_name,last_name,age,gender,major,absences,tutoring,parental_support,curriculum_activities
0,S001,Alice,Smith,22,Male,Computer Science,4,Yes,High,Art Club
1,S002,James,Johnson,24,Male,AI,2,Yes,Low,Coding Club
2,S003,Mia,Smith,21,Female,Computer Science,14,No,Low,Sports
3,S004,Noah,Garcia,22,Male,Computer Science,10,Yes,Low,Volunteer
4,S005,Alice,Garcia,23,Female,AI,14,Yes,Medium,NaN
...,...,...,...,...,...,...,...,...,...,...
95,S096,Mia,Jones,25,Male,Cyber Security,9,No,Medium,Coding Club
96,S097,James,Davis,25,Male,Software Engineering,1,No,High,Music
97,S098,Mia,Jones,18,Male,Computer Science,18,Yes,High,Music
98,S099,Mia,Smith,20,Female,Software Engineering,20,No,Medium,Sports
99,S100,Mia,Miller,25,Male,Cyber Security,11,No,Medium,Music

In [8]:
student_grade_data.head() #-- For first 5 rows --#

,student_id,first_name,last_name,age,gender,major,absences,tutoring,parental_support,curriculum_activities
0,S001,Alice,Smith,22,Male,Computer Science,4,Yes,High,Art Club
1,S002,James,Johnson,24,Male,AI,2,Yes,Low,Coding Club
2,S003,Mia,Smith,21,Female,Computer Science,14,No,Low,Sports
3,S004,Noah,Garcia,22,Male,Computer Science,10,Yes,Low,Volunteer
4,S005,Alice,Garcia,23,Female,AI,14,Yes,Medium,NaN

In [9]:
student_grade_data.tail() #-- For last 5 rows. --#

,student_id,first_name,last_name,age,gender,major,absences,tutoring,parental_support,curriculum_activities
95,S096,Mia,Jones,25,Male,Cyber Security,9,No,Medium,Coding Club
96,S097,James,Davis,25,Male,Software Engineering,1,No,High,Music
97,S098,Mia,Jones,18,Male,Computer Science,18,Yes,High,Music
98,S099,Mia,Smith,20,Female,Software Engineering,20,No,Medium,Sports
99,S100,Mia,Miller,25,Male,Cyber Security,11,No,Medium,Music

In [16]:
print(f"Shape of the {student_grade_data}: {student_grade_data.shape}")
print(f"Columns of the {student_grade_data}: {student_grade_data.columns}")
print(f"Detail of the {student_grade_data}: {student_grade_data.info()}")
print(f"Quick statstics of the file {student_grade_data} is: {student_grade_data.describe()}")

Shape of the    student_id first_name last_name  age  gender                 major  \
0        S001      Alice     Smith   22    Male      Computer Science
1        S002      James   Johnson   24    Male                    AI
2        S003        Mia     Smith   21  Female      Computer Science
3        S004       Noah    Garcia   22    Male      Computer Science
4        S005      Alice    Garcia   23  Female                    AI
..        ...        ...       ...  ...     ...                   ...
95       S096        Mia     Jones   25    Male        Cyber Security
96       S097      James     Davis   25    Male  Software Engineering
97       S098        Mia     Jones   18    Male      Computer Science
98       S099        Mia     Smith   20  Female  Software Engineering
99       S100        Mia    Miller   25    Male        Cyber Security

    absences tutoring parental_support curriculum_activities
0          4      Yes             High              Art Club
1          2      Yes              Low           Coding Club
2         14       No              Low                Sports
3         10      Yes              Low             Volunteer
4         14      Yes           Medium                   NaN
..       ...      ...              ...                   ...
95         9       No           Medium           Coding Club
96         1       No             High                 Music
97        18      Yes             High                 Music
98        20       No           Medium                Sports
99        11       No           Medium                 Music

[100 rows x 10 columns]: (100, 10)
Columns of the    student_id first_name last_name  age  gender                 major  \
0        S001      Alice     Smith   22    Male      Computer Science
1        S002      James   Johnson   24    Male                    AI
2        S003        Mia     Smith   21  Female      Computer Science
3        S004       Noah    Garcia   22    Male      Computer Science
4        S005      Alice    Garcia   23  Female                    AI
..        ...        ...       ...  ...     ...                   ...
95       S096        Mia     Jones   25    Male        Cyber Security
96       S097      James     Davis   25    Male  Software Engineering
97       S098        Mia     Jones   18    Male      Computer Science
98       S099        Mia     Smith   20  Female  Software Engineering
99       S100        Mia    Miller   25    Male        Cyber Security

    absences tutoring parental_support curriculum_activities
0          4      Yes             High              Art Club
1          2      Yes              Low           Coding Club
2         14       No              Low                Sports
3         10      Yes              Low             Volunteer
4         14      Yes           Medium                   NaN
..       ...      ...              ...                   ...
95         9       No           Medium           Coding Club
96         1       No             High                 Music
97        18      Yes             High                 Music
98        20       No           Medium                Sports
99        11       No           Medium                 Music

[100 rows x 10 columns]: Index(['student_id', 'first_name', 'last_name', 'age', 'gender', 'major',
       'absences', 'tutoring', 'parental_support', 'curriculum_activities'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             100 non-null    str
 1   first_name             100 non-null    str
 2   last_name              100 non-null    str
 3   age                    100 non-null    int64
 4   gender                 100 non-null    str
 5   major                  100 non-null    str
 6   absences               100 non-null    int64
 7   tutoring               100 non-null    str
 8   parental_support       100 non-null    str
 9   curriculum_activities  87 non-null     str
dtypes: int64(2), str(8)
memory usage: 7.9 KB
Detail of the    student_id first_name last_name  age  gender                 major  \
0        S001      Alice     Smith   22    Male      Computer Science
1        S002      James   Johnson   24    Male                    AI
2        S003        Mia     Smith   21  Female      Computer Science
3        S004       Noah    Garcia   22    Male      Computer Science
4        S005      Alice    Garcia   23  Female                    AI
..        ...        ...       ...  ...     ...                   ...
95       S096        Mia     Jones   25    Male        Cyber Security
96       S097      James     Davis   25    Male  Software Engineering
97       S098        Mia     Jones   18    Male      Computer Science
98       S099        Mia     Smith   20  Female  Software Engineering
99       S100        Mia    Miller   25    Male        Cyber Security

    absences tutoring parental_support curriculum_activities
0          4      Yes             High              Art Club
1          2      Yes              Low           Coding Club
2         14       No              Low                Sports
3         10      Yes              Low             Volunteer
4         14      Yes           Medium                   NaN
..       ...      ...              ...                   ...
95         9       No           Medium           Coding Club
96         1       No             High                 Music
97        18      Yes             High                 Music
98        20       No           Medium                Sports
99        11       No           Medium                 Music

[100 rows x 10 columns]: None
Quick statstics of the file    student_id first_name last_name  age  gender                 major  \
0        S001      Alice     Smith   22    Male      Computer Science
1        S002      James   Johnson   24    Male                    AI
2        S003        Mia     Smith   21  Female      Computer Science
3        S004       Noah    Garcia   22    Male      Computer Science
4        S005      Alice    Garcia   23  Female                    AI
..        ...        ...       ...  ...     ...                   ...
95       S096        Mia     Jones   25    Male        Cyber Security
96       S097      James     Davis   25    Male  Software Engineering
97       S098        Mia     Jones   18    Male      Computer Science
98       S099        Mia     Smith   20  Female  Software Engineering
99       S100        Mia    Miller   25    Male        Cyber Security

    absences tutoring parental_support curriculum_activities
0          4      Yes             High              Art Club
1          2      Yes              Low           Coding Club
2         14       No              Low                Sports
3         10      Yes              Low             Volunteer
4         14      Yes           Medium                   NaN
..       ...      ...              ...                   ...
95         9       No           Medium           Coding Club
96         1       No             High                 Music
97        18      Yes             High                 Music
98        20       No           Medium                Sports
99        11       No           Medium                 Music

[100 rows x 10 columns] is:               age   absences
count  100.000000  100.00000
mean    21.830000   10.56000
std      2.318372    6.55408
min     18.000000    0.00000
25%     20.000000    4.00000
50%     22.000000   11.00000
75%     24.000000   16.00000
max     25.000000   20.00000

In [22]:
#-- Take the n rows. --#
student_grade_data.iloc[89]
#-- Take from 0 to 10 row. --#
student_grade_data[0:10]
#-- Take specific row. --#
student_grade_data.iloc[[1, 3, 24, 26]]

,student_id,first_name,last_name,age,gender,major,absences,tutoring,parental_support,curriculum_activities
1,S002,James,Johnson,24,Male,AI,2,Yes,Low,Coding Club
3,S004,Noah,Garcia,22,Male,Computer Science,10,Yes,Low,Volunteer
24,S025,John,Johnson,18,Female,Data Science,3,Yes,Low,Sports
26,S027,Olivia,Wilson,19,Male,Software Engineering,0,Yes,Low,Sports

In [26]:
#-- Take all rows od the N column --#
student_grade_data.iloc[:, 1]
#-- Take the 0, 1 and 2 column. --#
student_grade_data.iloc[:, 0:3]   
#-- Take only 1 and 4 column --#
student_grade_data.iloc[:, [1, 4]]

   first_name  gender
0       Alice    Male
1       James    Male
2         Mia  Female
3        Noah    Male
4       Alice  Female
..        ...     ...
95        Mia    Male
96      James    Male
97        Mia    Male
98        Mia  Female
99        Mia    Male

[100 rows x 2 columns]

In [28]:
#-- Combine both row and column (1 cell only). --#
student_grade_data.iloc[0, 2]
#-- Take a range. --#
student_grade_data.iloc[0:5, 1:4]

  first_name last_name  age
0      Alice     Smith   22
1      James   Johnson   24
2        Mia     Smith   21
3       Noah    Garcia   22
4      Alice    Garcia   23

In [37]:
#-- Filter data. --#
age_filter = student_grade_data[student_grade_data["age"] >= 20]
age_filter.to_csv('age_filter.csv', encoding='utf-8-sig')

In [38]:
gender_filter = student_grade_data[student_grade_data["gender"] == "Female"]
gender_filter.to_csv('female_gender_filter.csv', encoding='utf-8-sig')

In [41]:
major_and_curriculum_activity = student_grade_data[(student_grade_data["major"] == "AI") & (student_grade_data["curriculum_activities"] == "Volunteer")]
major_and_curriculum_activity.to_csv('major_and_curriculum_activity.csv', encoding='utf-8-sig')